# Collection of all tasks known in a search and rescue mission

string EXPLORE = explore
string GO_TO = goTo
string EXPLORE_VICTIM_HYPOTHESIS = exploreVictimHypothesis
string APPROACH_VICTIM = approachVictim
string LOOK_AT = lookAt
string SUPPORT_VICTIM = supportVictim
string START = start

int8 INDEX_VICTIM_SUPPORT = 0
int8 INDEX_VICTIM_X = 1
int8 INDEX_VICTIM_Y = 2
int8 INDEX_VICTIM_Z = 3
int8 INDEX_VICTIM_DISTANCE = 4

int8 INDEX_START_DIRECTION = 0
int8 LEFT = 0
int8 RIGHT = 1
